name: Deploy to Namecheap via FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Build project
        run: npm run build

      - name: 🧪 Verify build output
        run: |
          echo "Build completed. Contents of dist folder:"
          ls -la dist/
          echo "Checking if index.html exists:"
          test -f dist/index.html && echo "✅ index.html found" || echo "❌ index.html missing"
          echo "Total files in dist: $(find dist -type f | wc -l)"

      - name: 📋 Create .htaccess for React Router
        run: |
          cat > dist/.htaccess << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteRule ^ index.html [QSA,L]
          
          # Security headers
          <IfModule mod_headers.c>
              Header always set X-Content-Type-Options nosniff
              Header always set X-Frame-Options DENY
              Header always set X-XSS-Protection "1; mode=block"
          </IfModule>
          
          # Compression
          <IfModule mod_deflate.c>
              AddOutputFilterByType DEFLATE text/plain
              AddOutputFilterByType DEFLATE text/html
              AddOutputFilterByType DEFLATE text/xml
              AddOutputFilterByType DEFLATE text/css
              AddOutputFilterByType DEFLATE application/xml
              AddOutputFilterByType DEFLATE application/xhtml+xml
              AddOutputFilterByType DEFLATE application/rss+xml
              AddOutputFilterByType DEFLATE application/javascript
              AddOutputFilterByType DEFLATE application/x-javascript
          </IfModule>
          EOF

      - name: 🚀 Deploy to Namecheap via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/
            README.md
            *.md
          dangerous-clean-slate: false
          dry-run: false
          log-level: verbose

      - name: 🎉 Deployment Success
        if: success()
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🌐 Your site should be available at: https://ecomotech.online"
          
      - name: 💥 Deployment Failed  
        if: failure()
        run: |
          echo "❌ Deployment failed. Please check the logs above."
          echo "Common issues:"
          echo "- Check FTP credentials in repository secrets"
          echo "- Verify server directory path"
          echo "- Ensure build completed successfully"
